# Generated by Django 2.2.1 on 2019-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_priceczk'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='priceEUR',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
